# Generated by Django 4.2.2 on 2023-06-09 20:57

import LiberOasis.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('publication', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_duration', models.IntegerField(default=30)),
                ('publish_year', models.IntegerField(default=2023)),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to=LiberOasis.utilities.upload_to)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=LiberOasis.utilities.upload_to)),
                ('stock', models.IntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(to='authors.author')),
            ],
        ),
    ]
